### PR TITLE
Main kustomize

### PR DESCRIPTION
**Pull request by mjarrett0**

### CODE REVIEW

**Comment by stencell** [comment]
@mjarrett0 What is this PR for? Can you please clean it up and close it?

**Comment by stencell** [comment]
@mjarrett0 Checking on this a final time before I close it.

cc @harpasin @rruizher if either of you know whether this is still needed or not.

**Comment by mjarrett0** [comment]
superfluous PR and can be closed

**Comment by mjarrett0** [comment]
I closed the PR.

thanks

**Pull request closed without merging**
